const LOGIN_USER = 'LOGIN_USER';
const ERROR_OCCURRED = 'ERROR_OCCURRED';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
const MAKE_TRANSACTION_SUCCESS = 'MAKE_TRANSACTION_SUCCESS';
const MAKE_TRANSACTION_ERROR = 'MAKE_TRANSACTION_ERROR';

export {
  LOGIN_USER,
  ERROR_OCCURRED,
  SIGN_UP_SUCCESS,
  SIGN_UP_ERROR,
  MAKE_TRANSACTION_SUCCESS,
  MAKE_TRANSACTION_ERROR,
};
