const LOGIN_USER = 'LOGIN_USER';
const ERROR_OCCURRED = 'ERROR_OCCURRED';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export { LOGIN_USER, ERROR_OCCURRED, SIGN_UP_SUCCESS, SIGN_UP_ERROR };
